const romanticQuotes = [
    "Kamu adalah bagian terbaik dari hari-hariku.",
    "Mencintaimu adalah hal termudah yang pernah kulakukan.",
    "Di matamu, aku menemukan rumah.",
    "Hampir dua tahun, dan rasanya aku makin jatuh cinta setiap harinya.",
    "Terima kasih sudah menjadi alasan senyumku, Zahra.",
    "Setiap detik bersamamu adalah memori yang ingin kuabadikan.",
    "Bukan tentang seberapa lama, tapi seberapa dalam kita saling memahami.",
    "Kamu adalah 'kebetulan' paling indah dalam hidupku.",
    "Melihatmu tertawa adalah kebahagiaan sedernahaku.",
    "Fikri dan Zahra, sebuah cerita yang ingin kutulis selamanya.",
    "Dunia terasa lebih baik karena ada kamu di dalamnya.",
    "Aku mencintaimu lebih dari kata-kata yang bisa kuucapkan.",
    "Kamu adalah lagu favorit yang tak pernah bosan kudengar.",
    "Denganmu, hal biasa terasa luar biasa.",
    "Hanya dengan menggenggam tanganmu, semua masalah terasa ringan.",
    "Tatap matamu adalah candu bagiku.",
    "Kamu melengkapi bagian dari diriku yang bahkan tak kutahu hilang.",
    "Aku akan selalu memilihmu, di kehidupan ini dan selanjutnya.",
    "Bersamamu adalah tempat favoritku.",
    "Cinta kita seperti bintang, tak selalu terlihat tapi selalu ada.",
    "Kamu membuatku ingin menjadi versi terbaik dari diriku.",
    "Terima kasih telah bertahan dan berjuang bersamaku.",
    "Hari ini, esok, dan selamanya, hatiku milikmu.",
    "Tawamu adalah melodi terindah di telingaku.",
    "Aku jatuh cinta padamu setiap kali aku melihat wajahmu.",
    "Tak ada tempat yang lebih nyaman selain di pelukanmu.",
    "Kamu adalah mimpi yang menjadi kenyataan.",
    "Cinta tidak butuh alasan, ia hanya butuh dirimu.",
    "Aku mencintaimu di setiap detak jantungku.",
    "Kamu adalah cahaya di hari-hariku yang gelap.",
    "Setiap kali aku memikirkan masa depan, aku melihatmu di sana.",
    "Kamu adalah anugerah terindah yang pernah kumiliki.",
    "Bersamamu, aku belajar apa arti cinta sejati.",
    "Tidak ada yang bisa menggantikan posisimu di hatiku.",
    "Kamu adalah awal dan akhir dari hari-hariku.",
    "Senyummu adalah alasan aku bersemangat menjalani hari.",
    "Aku bersyukur Tuhan mempertemukan kita.",
    "Kamu adalah pelangi setelah badai dalam hidupku.",
    "Di setiap doaku, namamu selalu kusebut.",
    "Aku mencintaimu tanpa syarat, Zahra.",
    "Setiap memori denganmu adalah harta karun bagiku.",
    "Kamu adalah puisi yang tak pernah selesai kutulis.",
    "Cinta kita sederhana, namun sangat bermakna.",
    "Aku tak butuh dunia, asalkan aku punya kamu.",
    "Kamu adalah alasan aku percaya pada cinta.",
    "Kehadiranmu mengubah segalanya menjadi lebih baik.",
    "Aku ingin menua bersamamu.",
    "Kamu adalah belahan jiwaku yang kutemukan.",
    "Cinta kita akan terus tumbuh, mengalahkan waktu.",
    "I love you, hari ini dan selamanya."
];