const ROMANTIC_QUOTES = [
  "Dalam ratusan hari yang telah kita lewati, setiap detiknya adalah rasa syukur yang tak berkesudahan.",
  "Kamu adalah bait puisi terbaik yang pernah ditulis takdir dalam hidupku.",
  "Dua tahun hampir berlalu, namun getaran saat pertama kali melihatmu masih sedalam ini.",
  "Menyayangimu adalah keputusan paling natural dan terbaik yang pernah kuambil.",
  "Bersamamu, riuhnya dunia seketika berubah menjadi simfoni yang menenangkan.",
  "Bukan tentang seberapa lama kita bersama, tapi tentang seberapa dalam kita saling bertumbuh.",
  "Kamu adalah rumah, tempat di mana seluruh lelahku luruh menjadi bahagia.",
  "Setiap senyummu adalah alasan utama di balik rasa syukurku setiap pagi.",
  "Dalam cerita kita, aku menemukan versi terbaik dari diriku sendiri.",
  "Terima kasih telah berjalan beriringan, melewati badai dan merayakan pelangi bersama.",
  "Kamu bukan sekadar pilihan; kamu adalah ketetapan hati yang paling indah.",
  "Dunia ini terlalu luas, namun hatiku selalu tahu jalan pulang menuju dekapmu.",
  "Bersamamu, waktu terasa berjalan terlalu cepat, namun kenangan terukir sangat dalam.",
  "Setiap percakapan kecil denganmu adalah bagian favorit dari hari-hariku.",
  "Cinta kita tidak butuh pembuktian dunia, cukup deru napas kita yang saling menjaga.",
  "Kamu adalah jawaban dari doa-doa sunyi yang sering kupanjatkan di sepertiga malam.",
  "Menatap matamu adalah cara terbaik untuk melihat masa depanku sendiri.",
  "Terima kasih untuk pelukan hangat di kala duniaku sedang tidak baik-baik saja.",
  "Kita adalah dua jiwa berbeda yang menemukan harmoni sempurna dalam kebersamaan.",
  "Hampir dua tahun, dan rasa ini tidak pernah berkurang, justru kian mengakar.",
  "Kamu membuat hal-hal biasa dalam hidup menjadi luar biasa indahnya.",
  "Dalam setiap tawa yang kita bagi, ada komitmen tersembunyi untuk selalu bersama.",
  "Jika waktu bisa diputar kembali, aku akan tetap memilih jalan yang membawaku kepadamu.",
  "Kamu adalah pelengkap dari setiap kekosongan yang dulu sempat menetap di dada.",
  "Cinta ini tumbuh tanpa dipaksa, mengalir tenang namun menghanyutkan ego kita.",
  "Genggaman tanganmu adalah jangkar yang menahanku di tengah badai kehidupan.",
  "Kamu adalah keindahan tersendiri di tengah dunia yang seringkali membingungkan.",
  "Setiap sudut kenangan kita selalu dipenuhi oleh aroma kebahagiaan.",
  "Terima kasih telah mencintaiku dengan segala kurang dan lebihku.",
  "Bersamamu, aku belajar bahwa cinta adalah tentang memberi tanpa pernah menghitung.",
  "Kamu adalah detak di dalam jantungku, yang menuntun setiap langkahku menuju bahagia.",
  "Melihatmu tertawa adalah pemandangan paling mewah yang bisa kunikmati gratis setiap hari.",
  "Dua tahun ini adalah bab terbaik dari buku kehidupanku yang panjang.",
  "Kamu membuatku percaya bahwa keajaiban itu nyata, dan wujudnya adalah kamu.",
  "Aku menyukai caramu melihat dunia, dan aku lebih menyukai caramu mencintaiku.",
  "Kita telah melukis kanvas ini dengan warna-warna terindah yang kita miliki.",
  "Rasa nyaman ini tidak pernah bohong; hatiku seutuhnya milikmu.",
  "Terima kasih telah menjadi pendengar terbaik dan pelindung paling setia.",
  "Kamu adalah fajar setelah malam panjang penuh ketidakpastian.",
  "Setiap pelukan darimu selalu berhasil menyembuhkan luka yang tak kasat mata.",
  "Cinta kita sederhana, namun makna di dalamnya teramat megah untuk dijabarkan.",
  "Aku ingin terus menua bersamamu, menghitung hari hingga rambut kita memutih.",
  "Kamu adalah melodi indah yang terus berputar di kepalaku tanpa henti.",
  "Bersamamu, aku tidak pernah takut menghadapi apa pun yang ada di depan.",
  "Setiap tempat yang kita kunjungi menjadi saksi bisu betapa dalamnya rasa ini.",
  "Kamu adalah kombinasi sempurna antara sahabat terbaik dan kekasih terhebat.",
  "Dua tahun hampir terlewati, dan aku masih jatuh cinta kepadamu setiap hari.",
  "Terima kasih telah membawa kehangatan yang tak pernah padam di hidupku.",
  "Kamu adalah takdir terbaik yang nyata, yang selalu ingin kujaga selamanya.",
  "Hari ini, esok, dan seterusnya, degup ini akan tetap membawa namamu."
];